################################################################################
#  CONFIGURATIONS FOR BINARY SEGMENTATION FOR A UNET WITH RESNET50 ENCODER
################################################################################

program:
    seed: 27

datamodule:
    data_dir: "data/train/samples"
    target_dir: "data/train/segments"
    test_data_dir: "data/test/samples"
    test_target_dir: "data/test/segments"
    batch_size: 16
    num_workers: 0

module:
    encoder_name: "resnet50"
    encoder_weights: "imagenet"
    in_channels: 1
    num_classes: 1
    loss: "dice"
    ignore_zeros: null
    jaccard_average: "macro"
    learning_rate: 0.004
    learning_rate_schedule_patience: 5

trainer:
    default_root_dir: "experiments/"
    fast_dev_run: False
    gpus: 1
    max_epochs: 100
    log_every_n_steps: 1
    # precision: 32
    auto_lr_find: True
    save_top_k: 2

logger:
    run_name: "[jasmin_run]_resnet50_imagenet_dice_auto_lr_batch16_lr_patience_5_eps_100"
    log_dir: "experiments/logs/"
